### ISSUE TITLE
Feature Request: Support Different Revision Levels

### ISSUE THREAD

**Issue by RayBB** [kevcodez/gradle-upgrade-interactive#1]
First, wow thank you so much for making this awesome program.
It works really great and is extremely helpful :)

The Gradle Versions Plugin supports selecting different [revision](https://github.com/ben-manes/gradle-versions-plugin#revisions) types.

Could you add support for that as well?

PS: The gif you uploaded seems to be broken/missing. If you upload it to github as a comment in an issue/PR then you can just use that instead of hosting it elsewhere.

**Comment by kevcodez** [comment]
Thanks for the feedback @RayBB. I will look into the revisions from the versions plugin and add support for it.

Will fix the gif aswell ;)

Edit: Fixed the gif

**Comment by kevcodez** [comment]
@RayBB Latest version 0.1.0 supports passing a revision with `-r` / `--revision`. Check the current README for further information.
