### ISSUE TITLE
Feature request : Report.json folder path can be modified

### ISSUE THREAD

**Issue by Dutta78** [kevcodez/gradle-upgrade-interactive#6]

**Comment by joergi** [comment]
I support this.
It would be nice to make this path configurable
thanks a lot

**Comment by joergi** [comment]
@kevcodez please have a look at the PR, this should fix it https://github.com/kevcodez/gradle-upgrade-interactive/pull/7 
but also be aware, I'm not a JS developer, so I wasn't really able to test that properly.

(I hope that project isn't dead yet)

**Comment by joergi** [comment]
@kevcodez could be closed I guess?
but still needs the push to npm too, it's there too!

**Comment by kevcodez** [comment]
Thanks for that! Just published 0.8.0
